### ISSUE TITLE
Can't select custom song title from list but other information on the left loads correctly

### ISSUE THREAD

**Issue by yardleyjd** [NyxTheShield/TrombLoader#15]
I'm trying to select the NYANYANYANYANYANYANYA... song but it immediately jumps to a different song if I select it, however, the info boxes to the left that have the description of the long are listed correctly and I can actually play the song.

![image](https://user-images.githubusercontent.com/46165257/196005697-4964eda1-3bea-473f-b46d-29bad91bc2ad.png)

Attached is the log
[Player.log](https://github.com/NyxTheShield/TrombLoader/files/9792990/Player.log)

**Comment by yardleyjd** [comment]
Found the issue, if the difficulty in the song.tmb file is greater than the number of stars (in this case it was 14) then it will cause an index out of range exception.

**Comment by legoandmars** [comment]
Fixed in [v1.3.0](https://github.com/NyxTheShield/TrombLoader/releases/tag/v1.3.0)
