### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by hoowwshii** [NyxTheShield/TrombLoader#40]
When I paste trombloader.dll file to bepinex/plugins folder, the game black screen, when i delete it, the game doesnt black screen.

[Message:   BepInEx] BepInEx 5.4.21.0 - TromboneChamp (2023/01/03 23:42:38)
[Info   :   BepInEx] Running under Unity v2019.3.11.13561645
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [TrombLoader 1.4.1]
[Info   :TrombLoader] Plugin TrombLoader is loaded!
[Message:   BepInEx] Chainloader startup complete

Here's the log file from bepinex, I tried v6 pre release and also 5.4.21 
OS: Windows 11 22H2 x64

**Comment by emmett-shark** [comment]
Update trombloader https://github.com/NyxTheShield/TrombLoader/releases/latest

**Comment by hoowwshii** [comment]
> Update trombloader https://github.com/NyxTheShield/TrombLoader/releases/latest

got it
