### ISSUE TITLE
for some reason my game looks like this and also is there a 100% save for this game

### ISSUE THREAD

**Issue by Pickymarker** [NyxTheShield/TrombLoader#8]
for some reason my game looks like this and also is there a 100% save for this game 
![image](https://user-images.githubusercontent.com/74084396/192981785-5695803a-4cbc-4207-a7c2-1caa1f70b43d.png)

**Comment by Pickymarker** [comment]
![image](https://user-images.githubusercontent.com/74084396/192985532-bddee027-449e-4c46-928b-270c6ac09a42.png)

**Comment by AssassinXgamingYT** [comment]
> for some reason my game looks like this and also is there a 100% save for this game ![image](https://user-images.githubusercontent.com/74084396/192981785-5695803a-4cbc-4207-a7c2-1caa1f70b43d.png)

your problem is when u converted you put wrong folder name :)

**Comment by legoandmars** [comment]
Folder name problem fixed in [v1.3.0](https://github.com/NyxTheShield/TrombLoader/releases/tag/v1.3.0)
